---
title: 'HW: Handling Corporate Data'
author: "Sanjiv Das"
date: "12/6/2016"
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

## Get All Firms Data

1. Download the table of firms listed on the NYSE, NASDAQ, and AMEX using the *quantmod* package.
2. What is the dimension of your data (rows, columns)?


## Clean Data

1. Remove all rows with incomplete data.
2. How many rows of observations do you now have?


## IPO Activity

1. Create a table of the frequency of IPOs by year to see hot and cold IPO markets. (First, remove all rows with missing IPO data.)
2. Plot IPO Activity with a bar plot. Make sure to label the axes properly. 
3. Plot IPO Activity using the **rbokeh** package to make a pretty line plot. See: https://hafen.github.io/rbokeh/




## Industry Sectors

1. How many sectors are there? 
2. Summarize the frequency of firms by sector. 


## Finance Sector

1. Subset the original data to include only finance firms. (Do not exclude rows of missing values.)
2. Sort the firms by market capitalization and print the top 50 finance firms. (Be careful, some of the values are in millions and others in billions.)


## Using the *Data Table* package

1. Install the *DT* package.
2. Show the top 50 financial firms using this package.


## Show the same using *Shiny* for finance firms

1. Redisplay the data set for finance firms using shiny.
2. Add to the shiny app a feature that lets you select which columns of the data set to display. The resulting Shiny App should look as follows: 

